# Declare your Buildkite pipelines below
---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-daveops-scratchpad
  description: Buildkite Pipeline for daveops-scratchpad
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/daveops-scratchpad

spec:
  type: buildkite-pipeline
  owner: group:eng-prod-engagement-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: daveops-scratchpad
      description: scratch pad repo for tests
    spec:
      repository: elastic/daveops-scratchpad
      pipeline_file: ".buildkite/pipeline.yml"
      teams:
        eng-prod-engagement-team:
          access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY
---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-bump-sh-examples
  description: Buildkite Pipeline for bump sh examples
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/bump-sh-examples

spec:
  type: buildkite-pipeline
  owner: group:eng-prod-engagement-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: bump-sh-examples
      description: scratch pad repo for tests
    spec:
      repository: elastic/daveops-scratchpad
      pipeline_file: ".buildkite/bump-sh.yml"
      teams:
        eng-prod-engagement-team:
          access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY
